### ISSUE TITLE
I am displaying this error in my wallet when `input for name`, you may need to fix this, why is this happening?

### ISSUE THREAD

**Issue by virjilakrum** [kkomelin/sui-dapp-starter#16]
<img width="357" alt="Ekran Resmi 2024-05-23 00 02 47" src="https://github.com/kkomelin/sui-dapp-starter/assets/158029357/af98646b-05be-4bee-9eb9-30e9503ccdcc">

**Comment by virjilakrum** [comment]
<img width="775" alt="Ekran Resmi 2024-05-23 01 20 36" src="https://github.com/kkomelin/sui-dapp-starter/assets/158029357/2fe97297-6124-4563-91c4-4dcde0a113d4">

ok ı understood thats why, sorry and good luck.

**Comment by kkomelin** [comment]
Thank for reporting this @virjilakrum. I'm happy to reconsider having this alias in the project demo but most of the official examples have such 0x0 aliases, so I just follow the common practice.

Anyway, feel free to report any other findings here. I'm at your service. And good luck with your project(s)!
