### ISSUE TITLE
'pnpm deploy:walrus' exiting early

### ISSUE THREAD

**Issue by mario4tier** [kkomelin/sui-dapp-starter#71]
**Problem statement**
Because of the following warning from site-builder, the script exit before the deployment is completed.
```[warn] Client/Server api version mismatch, client api version : 1.27.2, server api version : 1.31.1```

On my setup, that exit happens before "New site object ID: " is displayed.

**Proposed solution**
Do no exit the process on stderr lines starting with "[warn]".

In walrus-site-deploy.cjs:
```ts
 ...
 stderr.on('data', async (error) => {
      console.error(error)
      // Do not exit if the line starts with "[warn]"
      if (error.startsWith('[warn]')) {
        return
      }
      process.exit()
    })
```

**Comment by kkomelin** [comment]
Hey @mario4tier!
Thanks for proposing this change. I wish we could find a better way to get the error code / severity level but for now it's fine to have this condition. Will integrate it.

**Comment by kkomelin** [comment]
Applied the proposed change [here](https://github.com/kkomelin/sui-dapp-starter/commit/1c7238bb653dd7e6129e6f15d7677790bd5a8c2e)
